### PR TITLE
rename the branch 'master' to 'main'

### PR DESCRIPTION
**Pull request by sklin93**
Please see https://github.com/tensorflow/model-card-toolkit/issues/253 regarding renaming the default branch.

### CODE REVIEW

**Comment by codesue** [comment]
Hi @sklin93, thank you for this contribution! As google-cla bot mentioned, please sign a Contributor License Agreement (CLA) so we can take a look at your pull request. View this [CLA check summary](https://github.com/tensorflow/model-card-toolkit/pull/260/checks?check_run_id=10518169471) for more information.

**Comment by sklin93** [comment]
CLA signed! Please review and approve the pull request, thank you @codesue

**Review by codesue — COMMENTED** [review]
Thank you for working on this! Looks good in general, with a couple more places to update before merging:
- [contributing guide](https://github.com/tensorflow/model-card-toolkit/blob/master/CONTRIBUTING.md?plain=1#L129-L133) (rebase for newer version)
- [pull request template](https://github.com/tensorflow/model-card-toolkit/blob/master/.github/PULL_REQUEST_TEMPLATE.md?plain=1#L18)
- [Scikit Learn demo notebook](https://github.com/tensorflow/model-card-toolkit/blob/master/model_card_toolkit/documentation/examples/Scikit_Learn_Model_Card_Toolkit_Demo.ipynb?short_path=8890bf3#L54)
- [Standalone demo notebook](https://github.com/tensorflow/model-card-toolkit/blob/master/model_card_toolkit/documentation/examples/Standalone_Model_Card_Toolkit_Demo.ipynb?short_path=4883a59#L56)

**Comment by sklin93** [comment]
> Thank you for working on this! Looks good in general, with a couple more places to update before merging:
> 
> * [contributing guide](https://github.com/tensorflow/model-card-toolkit/blob/master/CONTRIBUTING.md?plain=1#L129-L133) (rebase for newer version)
> * [pull request template](https://github.com/tensorflow/model-card-toolkit/blob/master/.github/PULL_REQUEST_TEMPLATE.md?plain=1#L18)
> * [Scikit Learn demo notebook](https://github.com/tensorflow/model-card-toolkit/blob/master/model_card_toolkit/documentation/examples/Scikit_Learn_Model_Card_Toolkit_Demo.ipynb?short_path=8890bf3#L54)
> * [Standalone demo notebook](https://github.com/tensorflow/model-card-toolkit/blob/master/model_card_toolkit/documentation/examples/Standalone_Model_Card_Toolkit_Demo.ipynb?short_path=4883a59#L56)

Thank you for checking! All changed.

**Review by codesue — APPROVED** [review]

**Pull request merged**
